Readbytesb
doceme/py-spidev pull request #80
Opened 2019-02-20 16:47 UTC by aardvarkkrill

wow ... my first ever pull request!  Also my first ever python C-api foray.
So apologies if I've done anything stupid...

added readbytesb which returns a bytes object rather than a list.  This can, for example be fed directly into numpy.frombuffer giving more efficient transfer as no list needs to be built.

2019-02-21 18:29 UTC, doceme commented on spidev_module.c
> +    if (resultType == 2) { //existing bytearray
Please remove magic numbers (Add #define for `resultType`)

2019-02-21 18:30 UTC, doceme requested changes
Thanks for the PR! I will merge this if you replace the 0, 1, 2 `resultType` values with `#define`'s.

2019-02-22 14:48 UTC, aardvarkkrill commented
Good call on the magic numbers.  I think perhaps my refactoring is a bit heavy handed anyway, and I've changed it a bit.
I added another function (which is probably the one I should have written first) and I'll make a separate pull request for that... again I'm new here, sorry if this is wrong.

2025-09-25 09:37 UTC, fschrempf commented
Superseded by https://github.com/doceme/py-spidev/pull/83

2025-09-25 09:37 UTC, closed without merging